version: "3.8"
services:

  # database application service
  mysqldb:
    image: mysql:8.0
    container_name: database
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
      MYSQL_DATABASE: db
    ports:
      - "3307:3307"  
    volumes:
      - db:/var/lib/mysql

    # backend application service
  app:
    image: khiarianwar/anwarkhiari_5ds5:latest
    container_name: spring-application
    restart: on-failure
    ports:
      - "8088:8088"  # Maps port 8089 on host to 8089 on container
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8088
  # Frontend application service

volumes:
  db :
