services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: stationsky
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - stationsky-network

  backend:
    image: rinedlazreg353/rinedlazreg-g1-stationsky:latest
    container_name: backend-container
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/stationsky
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - stationsky-network

networks:
  stationsky-network:  # Corrected network name
    driver: bridge
